In [ ]:
import numpy as np


array_2d = np.array([[4, 3, 5],
                     [3, 7, 9],
                     [3, 7, 10]])

print("2D Array:")
print(array_2d)


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

# Create a 3D array (2x3x4)
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],

                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

print("3D array")
print(array_3d)

3D array
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
